const authentification = {
  email: "Email",
  password: "Mot de passe",
  password_confirm: "Confirmer le mot de passe",
  first_name: "Prénom",
  last_name: "Nom",
  username: "Nom d'utilisateur",
  phone: "Numéro de téléphone",
  year: "Année",
  sector: "Filière",
  forgot_password: "Mot de passe oublié ?",

  register: {
    title: "S'inscrire",
    register_with_google: "Continuer avec Google",
    register_with_facebook: "Continuer avec Facebook.tsx",
    register_with_apple: "Continuer avec Apple",
    register_with_unistra: "Continuer avec Unistra",
    link_with_unistra: "Lier son compte Unistra",
    submit: "Créer un compte",
    next: "Suivant",
    skip: "Passer cette étape",
    already_registered: "Déjà un compte ?",
    personal_informaions: "Informations personnelles",
    unistra_account: "Compte Unistra",
    accept_cgu: "Accepter les conditions d'utilisation",
    cgu: "Conditions d'utilisation",
  },
  login: {
    title: "Se connecter",
    login_with_google: "Se connecter avec Google",
    login_with_facebook: "Se connecter avec Facebook.tsx",
    login_with_apple: "Se connecter avec Apple",
    login_with_unistra: "Se connecter avec Unistra",
    submit: "Se connecter",
    not_registered: "Pas encore de compte ?",
  },
};

export default authentification;
