const ROUTES = {
  test: "/test",
  home: "/home",
  messages: "/messages",
  announcements: "/announcements",
  add_event: "/add_event",
  calendar: "/calendar",
  settings: "/settings",
  fouaille: "/fouaille",
  vizualisation: "/fouaille/vizualisation",
  auth: "/auth",
  login: "/auth/login",
  register: "/auth/register",
  forgot_password: "/auth/forgot_password",
  organizations: "/organizations",
  crousbot: "/crousbot",
  index: "/",
  publication: "/publication",
  profile: "/settings/profile",
  cts: "/cts",
  form: "/form",
  cgu: "/auth/cgu",
  credits: "/credits",
};

export default ROUTES;
