export const routes = {
  root: "/",
  home: "/home",
  dev: "/dev",
  organizations: "/organizations",
  create_post_step_1: "/create/post/step1",
  create_post_step_2: "/create/post/step2",
  create_event: "/create/event",
  create_both: "/create/both",
  auth: "/auth",
  sign_in: "/auth/sign-in",
  sign_up: "/auth/sign-up",
  forgot_password: "/auth/forgot-password",
  fouaille: "/fouaille",
  menu: "/menu",
  settings: "/settings",
  mps: "https://nextcloud.its-tps.fr/s/zfFkwR6y5wxt5gW",
  cgu: "/cgu",
};
