name: 'publish'
# on:
#   push:
#     tags:
#       - 'app-v0.*'

on: [push]

jobs:  
  build-app:
    runs-on: ${{ matrix.os }}
    name: Build ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ios, android]
        include:
          - platform: ios
            os: its-macos
          - platform: android
            os: its-linux

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup environment (node, pnpm, expo)
        uses: ./.github/workflows/setup
        with:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      
      - name: Set private eas.json (iOS only)
        if: matrix.platform == 'ios'
        run: echo '${{ secrets.EAS_JSON }}' > eas.json
        
      - name: 🚀 Build app
        run: eas build --platform ${{ matrix.platform }} --non-interactive --local

      - name: 📌 Nextcloud Artifact
        uses: trympet/nextcloud-artifacts-action@v2
        with:
          name: ${{ matrix.platform == 'ios' && 'app-ipa' || 'app-aab' }}
          path: build-*                                         
          nextcloud-url: ${{ secrets.NEXTCLOUD_URL }}           
          nextcloud-username: ${{ secrets.NEXTCLOUD_USERNAME }} 
          nextcloud-password: ${{ secrets.NEXTCLOUD_PASSWORD }} 